#Generic Configuration to be used by all servers
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

server:
  port: 8761