server:
  port: 8100
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_server_db
    username: anup
    password: anup
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  #Later we'll change the ports to our API Gateway port
  config:
    customer-server:
      url: http://localhost:8080/api/v1/customers
    product-server:
      url: http://localhost:8090/api/v1/products
    payment-server:
      url: http://localhost:8110/api/v1/payments