server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_server_db
    username: anup
    password: anup
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # We will be using Flyway for schema migration
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}