server:
  port: 8080
spring:
  data:
    mongodb:
      username: anup
      password: anup
      host: localhost
      port: 27017
      database: customer_server_db
      authentication-database: admin